modLoader="javafml"
loaderVersion="[45,)"
issueTrackerURL="https://github.com/Lothrazar/RootsClassic/issues"
license="MIT"

[[mods]]
modId="rootsclassic"
version="${file.jarVersion}"
displayName="Roots Classic"
displayURL="https://www.curseforge.com/minecraft/mc-mods/roots-classic"
updateJSONURL="https://raw.githubusercontent.com/Lothrazar/RootsClassic/trunk/1.18/update.json"
authors="Elucent, Lothrazar, Mrbysco"
description='''
Classic port of Roots, the Druidic Magic Mod
'''
[[dependencies.rootsclassic]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4,1.20)"
ordering="NONE"
side="BOTH"
[[dependencies.rootsclassic]]
modId="forge"
mandatory=true
versionRange="[45.1.0,)"
ordering="NONE"
side="BOTH"