modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Lothrazar/RootsClassic/issues"
license="MIT"

[[mods]]
modId="rootsclassic"
version="${file.jarVersion}"
displayName="Roots Classic"
displayURL="https://www.curseforge.com/minecraft/mc-mods/roots-classic"
updateJSONURL="https://raw.githubusercontent.com/Lothrazar/RootsClassic/trunk/1.20/update.json"
authors="Elucent, Lothrazar, Mrbysco"
description='''
Classic port of Roots, the Druidic Magic Mod
'''
[[dependencies.rootsclassic]]
	modId="minecraft"
	type="required"
  versionRange="[1.21,1.22)"
	ordering="NONE"
	side="BOTH"
[[dependencies.rootsclassic]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.1,]"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
#[[dependencies.rootsclassic]]
#    modId="flib"
#  type="required"
#    versionRange="[0.0.7,)"
#    ordering="NONE"
#    side="BOTH"